### ISSUE TITLE
Running with deploy_cdsw_model=true frequently causes build to fail

### ISSUE THREAD

**Issue by wcbdata** [asdaraujo/edge2ai-workshop#5]
Tim Spann reports during setup that deploying with deploy_cdsw_model=true (the default) causes the install to fail and leaves the cluster in an unusable state. 

Workaround is to set deploy_cdsw_model=false and have students run Lab 11 to set up CDSW model, but that can take 30-60 minutes.

**Comment by asdaraujo** [comment]
This has been improved. The CDSW model deployment is now done in the background and will not cause the deployment to fail.

The model deployment, however, may fail independently later on, but this is unlikely in my experience. If it fails, it usually fails for a reduce number of instances and it can be fixed manually
